apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: valid-policy
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
spec:
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - "*"
